### ISSUE TITLE
Type Error in Print Forwarding Table Method

### ISSUE THREAD

**Issue by berkeracir** [cengwins/ahc#6]
**Describe the bug**
I got type error when I tried to use **print_forwarding_table** method of **Topology** class.
```
Traceback (most recent call last):
  File "D:/Projects/ahc/tests/testmutualexclusion.py", line 64, in <module>
    main()
  File "D:/Projects/ahc/tests/testmutualexclusion.py", line 34, in main
    topology.print_forwarding_table()
  File "D:\Projects\ahc\Ahc.py", line 329, in print_forwarding_table
    print('\n'.join([''.join(['{:4}'.format(item) for item in row])
  File "D:\Projects\ahc\Ahc.py", line 329, in <listcomp>
    print('\n'.join([''.join(['{:4}'.format(item) for item in row])
TypeError: 'int' object is not iterable
```

**To Reproduce**
1. Use `Topology().print_forwarding_table()` or `topology.print_forwarding_table()`.

**Expected behavior**
I was expected to see forwarding table of the topology.

**Modules**
Ahc module, Topology class, print_forwarding_table method.

**Desktop:**
 - OS: Windows 10 (64-bit)
 - Python version: 3.8.8 within Anaconda environment with PyCharm

**Additional context**
I managed to fix the problem with the following lines:
```python
  def print_forwarding_table(self):
    registry.print_components()
    digits = int(math.log10(len(self.nodes) - 1) + 1)   # Assuming node ids are integers and starting from 0 to n.
    digitsFormat = '{:' + str(digits + 1) + '}'   # +1 is for spacing character between node ids in forwarding table.
    print('\n'.join([''.join([digitsFormat.format(destination) for destination in self.ForwardingTable[source]])
                     for source in self.ForwardingTable]))
```

**Comment by btezergil** [comment]
The print_forwarding_table() method was not updated when we changed the implementation of ForwardingTable. I did that in the commit, it works in my tests now. Can you test again with the updated code?

**Comment by berkeracir** [comment]
It's working now. However, if the topology has more than 1000 or 1001 nodes, forwarding table will be printed incorrectly due to `{:4}` format. I think it can be arranged dynamically.
