### ISSUE TITLE
Every Broadcast message has the same id

### ISSUE THREAD

**Issue by bibo7086** [cengwins/ahc#75]
**Describe the bug**
The broadcast message header in the Broadcasting file results to the default sequence number instead of the unique broadcast id. This results in each broadcast message having the same id. 

**To See**
Where does this occur?
1. Go to the Broadcasting file 
2. Scroll down to the senddownbroadcast function
3. Exactly when defining the header at `hdr = BroadcastingMessageHeader(BroadcastingMessageTypes.SIMPLEFLOOD, whosends, destination, nexthop, interfaceid, sequencenumber)`. 

**To Reproduce** 
Try Broadcasting a message using Controlled flooding. 

**Expected behavior**
Each broadcast message should have a unique identifier given to it when the on_broadcast function is triggered and determined by the "self.uniquebroadcastidentifier".

**Desktop:**
 - OS: Mac OS
 - Python version 3.9

**Workaround**
Adding a dummy interfaceid as follows should solve the problem 
`interfaceid = float('inf')  `  
`hdr = BroadcastingMessageHeader(BroadcastingMessageTypes.SIMPLEFLOOD, whosends, destination,
                                    nexthop, interfaceid, sequencenumber)`

**Comment by ARLEONTR** [comment]
Resolved as you defined....

**Comment by ARLEONTR** [comment]
Thank you
